version: "3.9"
services:
  app:
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
    tmpfs:
      - /tmp/pids/
    user: ${UID}:${GID}
  db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env